#!/usr/bin/env bash
# Transfer a file from a client to a server

if [ -z "$4" ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    scp -i "$4" "$1" "$3"@"$2":~/
fi
