#!/usr/bin/env bash
# Install nginx web server and redirect a page

sudo apt-get -y update
sudo apt-get -y install nginx

sudo chown -R "$USER":"$USER" /var/www/html
sudo echo "Hello World!" > /var/www/html/index.nginx-debian.html

repl_str="server_name _;\n\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "s/server_name _;/$repl_str/" /etc/nginx/sites-available/default

sudo service restart nginx
