#!/usr/bin/env bash
# Install and configure HAproxy on a load balancer server
# Configure HAproxy so that it send traffic to web-01 and web-02 servers
# Distribute requests using a roundrobin algorithm
# Make sure that HAproxy can be managed via an init script

repl_str="127.0.0.1 localhost 128867-lb-01\n34.232.68.127 128867-lb-01\n34.204.82.149 128867-web-01\n107.23.209.253 128867-web-02"
sudo sed -i "s/127.0.0.1 localhost 128867-lb-01/$repl_str/" /etc/hosts

sudo apt-get -y update
sudo apt-get -y install haproxy

# Ensure HAproxy can be managed via an init script
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

echo -e "\n# HAproxy for web servers\nfrontend web-frontend\n\tbind 34.232.68.127:80\n\tmode http\n\tdefault_backend web-backend\n\nbackend web-backend\n\tbalance roundrobin\n\tserver 128867-web-01 34.204.82.149:80 check\n\tserver 128867-web-02 107.23.209.253:80 check" | sudo tee -a /etc/haproxy/haproxy.cfg

sudo service haproxy restart
