#!/usr/bin/env bash
# Build on your task 0 solution: service (init) must say that nginx is not running
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
rm /var/run/nginx.pid
