#!/usr/bin/env bash
# FizzBuzz: Prints 1 to 100, replacing the number with FizzBuzz for multiples
#+ of 15, Fizz for multiples of 3 and Buzz for multiples of 5

i=1

while ((i <= 100)); do
	if (( ((i % 15)) == 0 )); then
		echo "FizzBuzz"
	elif (( ((i % 3)) == 0 )); then
		echo "Fizz"
	elif (( ((i % 5)) == 0 )); then
		echo "Buzz"
	else
		echo "$i"
	fi
	i=$((i + 1))
done
