#!/usr/bin/env bash
# Displays the content of the file /etc/passwd using the while loop and IFS

while IFS=":" read -r -a array; do
	echo "The user ${array[0]} is part of the ${array[3]} gang, lives in \
${array[5]} and rides ${array[6]}. ${array[2]}'s place is \
protected by the passcode ${array[1]}, more info about the \
user here: ${array[4]}"
done < /etc/passwd
