#!/usr/bin/env bash
# 4-if_9_say_hi: Demonstrate how use the while loop and the if statement

count=1

while [[ "$count" -le 10 ]]; do
	echo "Best School"
	if [ "$count" -eq 9 ]; then
		echo "Hi"
	fi
	count=$((count + 1))
done
