#!/usr/bin/env bash
# Configure nginx to be running as the user nginx and
# to be listening on all active ports on port 8080
sed -i 's/#user www-data;/user nginx;/' /etc/nginx/nginx.conf
sed -i 's/80 default_server/8080 default_server/' /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
# Kill Apache so it does not interfere with Nginx
pkill apache2
sudo -u nginx service nginx restart
